// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWa8OShxOy2OAmTfHTpc05f7DjaM04dsM',
    appId: '1:1033124090278:web:72c9f7024baad7aba7ff67',
    messagingSenderId: '1033124090278',
    projectId: 'habitapp-motimotiflower',
    authDomain: 'habitapp-motimotiflower.firebaseapp.com',
    storageBucket: 'habitapp-motimotiflower.firebasestorage.app',
    measurementId: 'G-F31S4W1ZT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXoDE_j_V_oKcwuhJ6QE7-2Xjhxf42bME',
    appId: '1:1033124090278:android:b067b522c414f688a7ff67',
    messagingSenderId: '1033124090278',
    projectId: 'habitapp-motimotiflower',
    storageBucket: 'habitapp-motimotiflower.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWa8OShxOy2OAmTfHTpc05f7DjaM04dsM',
    appId: '1:1033124090278:web:50fe367fefbbc6ada7ff67',
    messagingSenderId: '1033124090278',
    projectId: 'habitapp-motimotiflower',
    authDomain: 'habitapp-motimotiflower.firebaseapp.com',
    storageBucket: 'habitapp-motimotiflower.firebasestorage.app',
    measurementId: 'G-68F9DQKX60',
  );
}
